WXR\ContentBundle\Entity\BaseContent:
    type: mappedSuperclass
    fields:
        name:
            type: string
            length: 255
        description:
            type: string
            length: 255
        title:
            type: string
            length: 255
        content:
            type: text
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime
    lifecycleCallbacks:
        preUpdate: [ onPreUpdate ]
