WXR\ContentBundle\Entity\Content:
    type: entity
    table: wxr_content_content
    uniqueConstraints:
        UNIQ_name:
            columns: [ name ]
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToMany:
        tags:
            targetEntity: WXR\ContentBundle\Entity\Tag
            joinTable:
                name: wxr_content_tags
                joinColumns:
                  content_id:
                    referencedColumnName: id
                inverseJoinColumns:
                  tag_id:
                    referencedColumnName: id
