WXR\ContentBundle\Entity\BaseContent:
    type: mappedSuperClass
    fields:
        name:
            type: string
            length: 255
        description:
            type: string
            length: 255
        title:
            type: string
            length: 255
        content:
            type: text
