WXR\ContentBundle\Entity\Content:
    type: entity
    table: wxr_content_content
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    uniqueConstraints:
        UNIQ_name:
            columns: [ name ]
